### ISSUE TITLE
In /index.php, put FAQ/CONTACT link in the button.

### ISSUE THREAD

**Issue by achabill** [achabill/cpc#3]
The faq/contact link is out of (hanging under) the button.  
Tested with Edge.

**Comment by DanCarl857** [comment]
Stop testing with edge for now man

**Comment by lewizho99** [comment]
i have fixed it
i have resuced the font size alitle

**Comment by DanCarl857** [comment]
Hi achabill/cpc,
A message from Daniel Carlson was left on IQ Elite for you. 
Click here https://a.iqelite.com/j/NHVo5Q/iuc/ to read your message 


The IQ Elite Team



---------------------------------------------------------------------------
This message was meant for reply@reply.github.com. If you do not want to continue receiving such mails from IQ Elite, please click on this link: https://a.iqelite.com/common/unsubscribe/?code=cba0fbdc&email=reply@reply.github.com
IQ Elite is a service with main office: C/ Gran De Gràcia 15, 1a 1a, 08012 Barcelona, Spain.
---------------------------------------------------------------------------
