### ISSUE TITLE
Build the "past events" page

### ISSUE THREAD

**Issue by achabill** [achabill/cpc#5]
The current *past events* page is a **copy** of the *next event* page.

**Comment by lewizho99** [comment]
carlson workam noh...
den bill u fill in data...

**Comment by DanCarl857** [comment]
Abeg I have just replaced the coloring and changed the headings to match what I think will be on the past events page. Will go into more additions today. I need some.....any....data.

**Comment by DanCarl857** [comment]
Also I was thinking we should create facebook and google+ pages so the social links lead to these pages for CPC. If that is ok Jafar just tell me or create them yourself and give us the links.
