### ISSUE TITLE
Move timeline from *next event* to *overview*

### ISSUE THREAD

**Issue by achabill** [achabill/cpc#6]
The overview page should contain a time line of the CPC year. That is, a time line of main events from opening of registration, to qualification round to final round to the close of the year.
On the other hand, in the *next event* page, there would be an agenda for the 2 main events dates detailing the particular day.  
You will be later provided with data for the agenda.

**Comment by lewizho99** [comment]
provide now

**Comment by DanCarl857** [comment]
Lol bt provide now
Lewis can't see your changes

**Comment by DanCarl857** [comment]
Will work on labeling and fixing the contact page. Still don't have data
for that though

**Comment by DanCarl857** [comment]
Hi achabill/cpc,
A message from Daniel Carlson was left on IQ Elite for you. 
Click here https://a.iqelite.com/j/NHVo5Q/7ga/ to read your message 


The IQ Elite Team



---------------------------------------------------------------------------
This message was meant for reply@reply.github.com. If you do not want to continue receiving such mails from IQ Elite, please click on this link: https://a.iqelite.com/common/unsubscribe/?code=8a84f960&email=reply@reply.github.com
IQ Elite is a service with main office: C/ Gran De Gràcia 15, 1a 1a, 08012 Barcelona, Spain.
---------------------------------------------------------------------------

**Comment by DanCarl857** [comment]
Hello,

Jack Ryan  started using IQ Elite. He  wrote you a message.

To read the message before it expires, just click on this link: https://a.iqelite.com/entry/new_message/2beaa04b7aa20f5827489c2d3fda9e1f544b80bfb/320c612f7502e5151899083b0bec47cb7a9cb59bd587491b68967b7c489907460a86d515f749082746d6d5f7b74745182515f60af83c49060b7cb51515151515151585866666ebd5183c49060a8587b91b7c4518accaf6d60b0a8c320c612f75044d3e22edb35af44b80bfb/

Read your message before it expires!            

Regards,
IQ Elite Team



---------------------------------------------------------------------------
This message was meant for reply@reply.github.com. If you do not want to continue receiving such mails from IQ Elite, please click on this link: https://a.iqelite.com/common/unsubscribe/?code=8a84f960&email=reply@reply.github.com
IQ Elite is a service with main office: C/ Gran De Gràcia 15, 1a 1a, 08012 Barcelona, Spain.
---------------------------------------------------------------------------
